### ISSUE TITLE
What is the base LLM of StockGPT?

### ISSUE THREAD

**Issue by cehao628** [AlphaFin-proj/AlphaFin#1]
What is the base LLM of StockGPT?

**Comment by xpl000-ctrl** [comment]
> What is the base LLM of StockGPT?StockGPT 的基础LLM是什么？

Have you solved the question? I want to know too.

**Comment by kakeru13468** [comment]
look like ChatGLM

**Comment by jackyideal** [comment]
ChatGLM2-6b
