### ISSUE TITLE
Missing necessary files

### ISSUE THREAD

**Issue by dangxuanvuong98** [AlphaFin-proj/AlphaFin#3]
Hi, I'm trying to run your source code, however, I get an error message on stage 1, after tracing I discovered that this repository is missing the files './output/stockgpt.json', ". /output/mldl_prediction.xlsx" - those used in module 'stage1_trend_prediction/dataprocess_stockgpt.py'. Please add them or show me how to generate similar files, thank you.

**Comment by xie85** [comment]
您好，我也有这个问题，请问您解决了吗？

**Comment by LZYSaltedFish** [comment]
Please refer to this [issue](https://github.com/AlphaFin-proj/AlphaFin/issues/5), bug has been fixed now.
