### ISSUE TITLE
缺乏必要文件怎么办？

### ISSUE THREAD

**Issue by xie85** [AlphaFin-proj/AlphaFin#5]
您好，我运行您的源代码stage1时候遇到了如下问题：
缺少文件“./output/stockgpt.json”、“./output/mldl_prediction.xlsx” - 模块“stage1_trend_prediction/dataprocess_stockgpt.py”中使用的文件。请问怎么办啊，求作者大哥回复一下

**Comment by LZYSaltedFish** [comment]
Sorry, the script cannot be run directly due to our lack of checks. At present, the problem has been fixed. The stage1_testdata.json and mldl_prediction.xlsx have been added to this repo, and the db files has been added to huggingface. You can follow the instructions in the README.
