### ISSUE TITLE
完全无法复现  请问是真的开源吗

### ISSUE THREAD

**Issue by wangsheng1991** [AlphaFin-proj/AlphaFin#6]

**Comment by xunmenglt** [comment]
你好,请问复现成功了吗

**Comment by jackyideal** [comment]
Will be uploaded soon

**Comment by LZYSaltedFish** [comment]
Of course, our models, datasets, framework and prompts are all open. There is just a bug in the end-to-end execution script for stage-1. Problem has now been fixed. If there are no other questions, we will close this issue.
