### ISSUE TITLE
缺少文件，无法运行

### ISSUE THREAD

**Issue by jensen-Shen-Li** [AlphaFin-proj/AlphaFin#8]
作者您好！

感谢你们的开源！

请问，我在运行stage1_trend_prediction.sh脚本的时候，报错 [Errno 2] No such file or directory: '../outputs/stockgpt_prediction.jsonl'，这个是因为没有提供这个文件吧？

**Comment by henrywang1205** [comment]
Did you solve this issue? 
I have similar situation as yours.
